[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ade"
version = "1.0.0"
description = "Active Directory Enumeration Script"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "termcolor>=2.0.1",
]

[project.optional-dependencies]
tools = [
    "netexec @ git+https://github.com/Pennyw0rth/NetExec",
    "certipy @ git+https://github.com/ly4k/Certipy.git",
    "bloodyad @ git+https://github.com/CravateRouge/bloodyAD.git",
    "bloodhound-ce",
    "impacket",
]

[project.scripts]
ade = "ade:main"
